spring:
  datasource:
    hikari:
      auto-commit: true
      connection-timeout: 6000
      maximum-pool-size: 5
    password: root
    url: jdbc:mysql://localhost:3306/customer
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect       
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
server:
  port: 0
  error:
    include-message: always    
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/    
